---
# Tasks file for roles/apt_update

- name: APT update
  apt:
    update_cache: true
    force_apt_get: true
    cache_valid_time: 3600

- name: APT upgrade
  apt:
    upgrade: dist
    force_apt_get: true
    autoremove: yes
    autoclean: yes
  register: aptupgrade

#- name: APT autoclean
#  apt:
#    autoclean: true
#  register: aptautoclean

#- name: APT autoremove
#  apt:
#    autoremove: true
#  register: aptautoremove

- name: APT record changes
  shell: grep -E "^$(date +%Y-%m-%d).+ (install|upgrade|remove) " /var/log/dpkg.log |cut -d " " -f 3-5
  register: aptchanges
  when: aptupgrade.changed

- name: APT report changes
  debug: msg="{{ aptchanges.stdout_lines }}"
  when: aptupgrade.changed

- name: Check for reboot
  register: reboot_required_file
  stat:
    path: /var/run/reboot-required
    get_md5: false

- name: Reboot
  reboot:
    msg: "Reboot initiated by Ansible after update/upgrade."
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 5
    post_reboot_delay: 30
    test_command: uptime
  when: reboot_required_file.stat.exists

