---
# tasks file for raspberry_tools

- name: Install preferrred packages
  ansible.builtin.package:
    name:
      - git
      - jq
      - libraspberrypi-bin
      - lsof
      - mc
      - minicom
      - openvpn
      - raspi-config
      - rrdtool
      - screen
      - sl
      - stress
      - stress-ng
      - sysbench
      - tcpdump
      - tcptraceroute
      - tmux
    state: latest

- name: Install preferrred packages (Ubuntu only)
  ansible.builtin.package:
    name:
      - ansible
      - wiringpi
    state: latest
  when:
    - ansible_distribution == 'Ubuntu'
