---
# handlers file for roles/raspberry_ntp

- name: raspberry_ntp_restart
  service:
    name: ntp
    state: restarted

- name: raspberry_ntpdate_enabled
  service:
    name: ntpddate.service
    enabled: true
