#!/bin/bash

#	Use rrdtool to keep track of a local Envoy-S-Standard-EU
#	(C) 2022, Hugo van der Kooij
#	requires:
#		Envoy-S in you local network
#		bash, curl, jq, rrdtool

#	Local variables
#
# IP of the Envoy system in local network
EnvoyIP=192.168.2.51
# Where do we store stuff?
DataDir=$HOME/Envoy
# Max Power output of system you ever expect?
MaxWattsNow=8000
# max Power production per day you ever expect?
MaxWattHoursToday=100000
MaxWattHoursSevenDays=100000

#	Initializing

# Check for existing DataDir, create it if needed
if [ ! -d $DataDir ]
then
	mkdir -p $DataDir
fi

# Check For existing RRD files, create them if needed
# Live Power output
if [ ! -f $DataDir/wattsNow.rrd ]
then
	rrdtool create $DataDir/wattsNow.rrd --step 60 \
		DS:wattsNow:GAUGE:60:0:$MaxWattsNow \
		RRA:AVERAGE:0.5:1m:90d \
		RRA:AVERAGE:0.5:1h:18M \
		RRA:AVERAGE:0.5:1d:7y 
#		RRA:AVERAGE:0.5:7d:10y
fi

# Power output today
if [ ! -f $DataDir/wattHoursToday.rrd ]
then
	rrdtool create $DataDir/wattHoursToday.rrd --step 60 \
		DS:wattHoursToday:GAUGE:60:0:$MaxWattHoursToday \
		RRA:AVERAGE:0.5:1m:90d \
		RRA:AVERAGE:0.5:1h:18M \
		RRA:AVERAGE:0.5:1d:7y 
fi

# Power output for a week
if [ ! -f $DataDir/wattHoursSevenDays.rrd ]
then
	rrdtool create $DataDir/wattHoursSevenDays.rrd --step 60 \
		DS:wattsHoursSevenDays:GAUGE:60:0:$MaxWattHoursSevenDays \
		RRA:AVERAGE:0.5:1m:90d \
		RRA:AVERAGE:0.5:1h:18M \
		RRA:AVERAGE:0.5:1d:7y 
fi

# Power output Lifetime
if [ ! -f $DataDir/wattHoursLifetime.rrd ]
then
	rrdtool create $DataDir/wattHoursLifetime.rrd --step 60 \
		DS:wattsHoursLifetime:COUNTER:60:0:4294967295 \
		RRA:AVERAGE:0.5:1m:90d \
		RRA:AVERAGE:0.5:1h:18M \
		RRA:AVERAGE:0.5:1d:7y 
fi

#	Production

# Live Power Output
EnvoyNow=`curl -s http://$EnvoyIP/api/v1/production`
wattsNow=`jq .wattsNow <<< $EnvoyNow`
wattHoursToday=`jq .wattHoursToday <<< $EnvoyNow`
wattHoursSevenDays=`jq .wattHoursSevenDays <<< $EnvoyNow`
wattHoursLifetime=`jq .wattHoursLifetime <<< $EnvoyNow`
#echo "Now:	$wattsNow W"
#echo "Today:	$wattHoursToday Wh"
#echo "Week:	$wattHoursSevenDays Wh"
#echo "Total:	$wattHoursLifetime Wh"
rrdtool update $DataDir/wattsNow.rrd N:$wattsNow
rrdtool update $DataDir/wattHoursToday.rrd N:$wattHoursToday
rrdtool update $DataDir/wattHoursSevenDays.rrd N:$wattHoursSevenDays
rrdtool update $DataDir/wattHoursLifetime.rrd N:$wattHoursLifetime

# The End
